name: Deploy Vite App

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 下載你的程式碼
      - name: Checkout
        uses: actions/checkout@v4

      # 安裝 Node.js
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 安裝套件
      - name: Install dependencies
        run: npm install

      # 編譯 React + TypeScript
      - name: Build
        run: npm run build

      # 上傳 dist
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist


  deploy:
    environment:
      name: github-pages

    runs-on: ubuntu-latest

    needs: build

    permissions:
      pages: write
      id-token: write

    steps:
      # 發布網站
      - name: Deploy
        uses: actions/deploy-pages@v4
